# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_profile_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='identifier',
        ),
    ]
