# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20161029_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_published'),
        ),
    ]
