# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_auto_20161029_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(to='tweets.Follower')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
