# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20161101_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Profile',
        ),
    ]
